### PR TITLE
Update be-by.json

### PR DESCRIPTION
**Pull request by Dzi-Mieha**
correcting grammatical errors

### CODE REVIEW

**Comment by SupertigerDev** [comment]
thanks!

**Comment by 1enify** [comment]
Wait, that weren't gramatical mistakes.

I translated to Belarusian Narkamauka, the renewed grammar, @Dzi-Mieha changed everything according to the classical one, Tarashkevitsa. Or are you that radical that you don't recognise Narkamauka? lol

But really, I don't mind it, also it would be nice of @SupertigerDev to change the flag to the traditional one(red-white-red)

**Comment by 1enify** [comment]
Wait, that weren't gramatical mistakes.

I translated to Belarusian Narkamauka, the renewed grammar, @Dzi-Mieha changed everything according to the classical one, Tarashkevitsa. Or are you that radical that you don't recognise Narkamauka? lol

But really, I don't mind it, also it would be nice of @SupertigerDev to change the flag to the traditional one(red-white-red)

Edit: yeah I checked the edits and turns out I really messed up in some places...(even in Narkamauka translation) Thanks for the corrections, Dzi-Mieha!

**Comment by 1enify** [comment]
Just one place that needs to be corrected

**Pull request merged**
