### PR TITLE
Programming Language Icons

### PR DESCRIPTION
**Pull request by F-iiral**
Added programming language icons to code boxes. They are .svg's of size 24x24px. All icons were either created by me or taken and modified from https://marketplace.visualstudio.com/items?itemName=JonathanHarty.gruvbox-material-icon-theme

### CODE REVIEW

**Comment by SupertigerDev** [comment]
Seems good, thanks :D

**Comment by SupertigerDev** [comment]
Is this PR ready to merge?

**Comment by F-iiral** [comment]
Yes, I did not test every single language but I am very sure it should work with all of them.

**Comment by SupertigerDev** [comment]
Alright thanks!

**Pull request merged**
